### ISSUE TITLE
Creación de componentes 

### ISSUE THREAD

**Issue by RaelRGB** [SistemasTecTlaxiaco/Creacion-_de-_componentes_Rael#1]
[RaelComponentesPersonalizados.pdf](https://github.com/SistemasTecTlaxiaco/Creacion-_de-_componentes_Rael/files/8342089/RaelComponentesPersonalizados.pdf)

**Comment by JudithReynaCS** [comment]
Calificación:17.4%

**Comment by josealfredo79** [comment]
Si bien hecho y revisado...
